"""
File that contains all the configuration costants.

Args:
    CODEQL_CLI (str): command to invoke CodeQL CLI
    CODEQL_DB_PATH (str): CodeQL database directory
    QUERY_PACK (str): path to the local CodeQL queries
    OUTPUT_QUERIES_PATH (str): directory to save the queries generated by the CreatorAgent
"""

from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

CODEQL_CLI = "codeql"
CODEQL_DB_PATH = "codeql_db"
QUERY_PACK = str(Path.home() / ".codeql/packages/codeql/python-queries/1.6.8/codeql-suites/python-security-and-quality.qls")
OUTPUT_QUERIES_PATH = "./generated_queries"
