"""
Module that implements all the tools used by the Agents.

Tools:
    - CodeQLSastTool: created a CodeQL database and run SAST analysis 
    - ParseSarifTool: parses the SARIF reports into structured JSON fro LLM
    - WebSearchTool: performs web searches and returns the top 5 results
    - WriteQuerySubAgent: generates CodeQL queries for a given CWE
    - FinishTool: marks the completion of the CreatorAgent
    - FinishToolSuggestor: marks the completion of the SuggestorAgent

Workflow:
    1. Source code is analyzed using CodeQLSastTool
    2. SARIF results are parsed by ParseSarifTool
    3. WebSearchTool can be invoked to gather context or insights
    4. CreatorAgent uses WriteQuerySubAgent and FinishTool to generate queries iteratively.

Args:
    Each tool class takes specific arguments as defined in their respective docstrings.
"""

import os
import json
import requests
from bs4 import BeautifulSoup
import html2text
import re
import time

from typing import List, Dict, Any
from pydantic import BaseModel, Field


class ParseSarifTool(BaseModel):  
    """
    Tool to parse SARIF report and produced JSON results for LLM processing.

    Args:
        sarif_filepath (str): path to SARIF JSON file
    """

    sarif_filepath: str = Field(description="Path to the SARIF JSON file generated by CodeQL.")
    
    def extract_cwes_from_rule(self, rule: Dict[str, Any]) -> List[str]:
        """Extract CWE identifiers from a SARIF rule definition."""
        cwes: List[str] = []

        tags = rule.get("properties", {}).get("tags", []) or []
        for tag in tags:
            if isinstance(tag, str) and tag.lower().startswith("external/cwe/cwe-"):
                num = tag.split("external/cwe/cwe-")[-1]
                num = re.sub(r"\D", "", num)
                if num:
                    cwes.append(f"CWE-{num}")

        for rel in rule.get("relationships", []) or []:
            target_id = (rel.get("target") or {}).get("id")
            if isinstance(target_id, str) and target_id.upper().startswith("CWE-"):
                num = re.sub(r"\D", "", target_id)
                if num:
                    cwes.append(f"CWE-{num}")

        help_md = (rule.get("help") or {}).get("markdown") or ""
        help_txt = (rule.get("help") or {}).get("text") or ""
        blob = f"{help_md}\n{help_txt}"
        for m in re.findall(r"\bCWE-(\d{1,5})\b", blob, flags=re.IGNORECASE):
            cwes.append(f"CWE-{m}")

        seen = set()
        out: List[str] = []
        for c in cwes:
            if c not in seen:
                seen.add(c)
                out.append(c)
        return out


    def run(self) -> str:
        """
        Reads the SARIF file and returns structured JSON.
        
        Returns:
            str: structured JSON string of results.
        """
        if not os.path.exists(self.sarif_filepath):
            raise Exception(f"ERROR: File '{self.sarif_filepath}' does not exist.")
        
        with open(self.sarif_filepath, 'r', encoding='utf-8') as f:
            sarif_data = json.load(f)
        
        structured_res: List[Dict[str, Any]] = []
        
        for runn in sarif_data.get('runs', []):
            tool = runn.get('tool', {})
            tool_name = tool.get('driver', {}).get('name', 'CodeQL')

            
            rules_id: Dict[str, Dict[str, Any]] = {}
            components = []
            driver = tool.get("driver")
            if isinstance(driver, dict):
                components.append(driver)
            
            exts = tool.get("extensions", []) or []
            for ext in exts:
                if isinstance(ext, dict):
                    components.append(ext)

            for component in components:
                for rule in component.get('rules', []):
                    rid = rule.get('id')
                    if isinstance(rid, str) and rid:
                        rules_id[rid] = rule

            for result in runn.get('results', []):
                rule_id = result.get('ruleId') or 'unknown_rule'
                rule_def = rules_id.get(rule_id, {}) or {}
                tags = rule_def.get('properties', {}).get('tags', []) or []
              
                if tags and 'security' not in tags:
                    continue


                cwes = self.extract_cwes_from_rule(rule_def)
                if not cwes:
                    cwes = ["CWE-Unknown"]
               
                message = (result.get('message') or {}).get('text') or 'No description'
                
                locations = []

                for loc in result.get("locations", []) or []:
                    phys = loc.get('physicalLocation') or {}
                    art = phys.get('artifactLocation') or {}
                    reg = phys.get('region') or {}
                    locations.append({
                        "uri": art.get("uri", "unknown_file"),
                        "line": reg.get("startLine")
                    })
                    

                structured_res.append({
                    'tool': tool_name,
                    'rule_id': rule_id,
                    'cwe': cwes,
                    'message': message,
                    'locations': locations
                })
        
        if not structured_res:
            print("\n\nWARNING: no security findings extracted from SARIF.")

        return json.dumps(structured_res, indent=2)


from ddgs import DDGS
"""
Exaple usage of DDGS:
results = DDGS().text('live free or die', region='wt-wt', safesearch='off', timelimit='y', max_results=10)

print(results)
[
    {
        "title": "News, sport, celebrities and gossip | The Sun",
        "href": "https://www.thesun.co.uk/",
        "body": "Get the latest news, exclusives, sport, celebrities, showbiz, politics, business and lifestyle from The Sun",
    }, ...
]
"""

class WebSearchTool(BaseModel):
    """
    Tool to perform web searches and return top 5 results.
    
    Args:
        query (str): search query string
        cwe (str): optional target CWE for routing search memory (e.g. "CWE-89")
    """

    query: str = Field(description="The search query (e.g., 'CodeQL python CWE-89 sink source names')")
    cwe: str = Field(default="", description="Optional CWE id associated with this search (e.g., 'CWE-89').")

    def run(self) -> str:
        """
        Performs the search and returns results as JSON with retry logic.

        Returns:
            str: JSON string of search results or error message
        """
        max_retries = 3
        base_delay = 2  # seconds

        for attempt in range(max_retries):
            try:
                results = DDGS().text(f"site:codeql.github.com OR site:github.com {self.query}", max_results=3)
                h = html2text.HTML2Text()  # in modo da preservare la sintassi di codeql
                h.ignore_links = True
                h.ignore_images = True

                final_context = []

                for res in results:
                    url = res['href']
                    try:
                        response = requests.get(url, timeout=10)
                        response.raise_for_status()  # Raise exception for bad status codes
                        soup = BeautifulSoup(response.text, 'html.parser')

                        for junk in soup(['nav', 'footer', 'header', 'script', 'style']):
                            junk.decompose()

                        texy_md = h.handle(str(soup))

                        final_context.append(f"SOURCE: {url}\nCONTENT:\n{texy_md[:3000]}")
                    except requests.exceptions.RequestException as e:
                        print(f"Warning: Failed to fetch {url}: {str(e)}")
                        continue
                    except Exception as e:
                        print(f"Warning: Error processing {url}: {str(e)}")
                        continue

                if final_context:
                    return "\n---\n".join(final_context)
                else:
                    return "No results could be fetched from the search."

            except Exception as e:
                if attempt < max_retries - 1:
                    delay = base_delay * (2 ** attempt)  # Exponential backoff
                    print(f"Search attempt {attempt + 1} failed: {str(e)}. Retrying in {delay}s...")
                    time.sleep(delay)
                else:
                    return f"Error: All {max_retries} search attempts failed. Last error: {str(e)}"

        return "Error: Maximum retries exceeded"

class VulnReport(BaseModel):
    """
    Structured report for FinishTool
    """
    cwe: str = Field(...)
    cwe_description: str = Field(...)
    line: int = Field(...)

class AnalysisReport(BaseModel):
    """
    Report for file analysis
    """
    vulnerabilities: List[VulnReport] = Field(default_factory=list)


class FinishTool(BaseModel):
    """Tool to signal completion and generate query suite."""
    final_report: AnalysisReport = Field(...)
