"""
Module that implements the ActionProcedure, a core reasoning component of the ReAct agent.

The ActionProcedure:
    - receive the current summary, agent thought and last reasoning step
    - formats a prompt combining context, summary and thought
    - invokes the LLM to produce the next action
    - returns the action wrapped in a structural ActionModel
    
"""

from agents_dir.base_agent import ReActChain
from procedures.base_procedure import BaseProcedure

from typing import Dict, Any, Type, Union
from pydantic import BaseModel, Field, create_model
from langchain_core.messages import SystemMessage


class ActionModel(BaseModel):
    """
    Represents an action generated by the agent's reasoning step.
    
    Attributes:
        action (Any): action chosen by the LLM.

    Methods:
        create(cls, actions): dinamically creates a Pydantic model supporting an union of possibile actions.

    """
    action: Any = Field(...)

    class Config:
        @staticmethod
        def json_schema_extra(schema: Dict[str, Any], model: Type['ActionModel']) -> None:
            for prop in schema.get('properties', {}).values():
                prop.pop('title', None)

    @classmethod
    def create(cls, actions):
        return create_model(
            cls.__name__,
            action=(Union[tuple(actions)], Field(...)),
            __base__=cls
        )


class ActionProcedure(BaseProcedure):
    """A reasoning procedure that invokes the LLM to produce an action based on 
    the thought and context summary.

    This class extends the BaseProcedure to handle reasoning and action production. 
    It leverages a summary of the scratchpad, the last reasoning step, and the 
    agent's thoughts to generate actions using the LLM.

    Args:
        llm: the LLM responsible for executing tasks based on the prompt.
        prompt_template (str): the prompt template that will be formatted and used as input to the LLM.

    Attributes:
        llm: the LLM responsible for executing tasks based on the prompt.
        prompt_template (str): the prompt template that will be formatted and used as input to the LLM.

    Methods:
        run(summary, last_step, thought, actions): generates actions based on the given inputs using the LLM.
    """

    def run(self, summary: str, scratchpad: list, last_step: ReActChain, thought: str, actions: list):
        """Executes the action reasoning procedure based on the current context.

        This method formats the prompt using the given summary, the previous step 
        in the reasoning process (last_step), and the agent's current thought. 
        It then invokes the LLM to generate appropriate actions.

        Args:
            summary (str): the produced summary for the current chain.
            last_step (ReActChain): the last step in the reasoning chain, representing the agent's prior thought process.
            thought (str): the produced thought for the current chain
            actions (list): list of the tools the agent has to choice. Each tool is an instance of autopenbench.Tools

        Returns:
            ActionModel: The ActionModel formatted by the LLM
        """
     
        prompt_content = self.prompt_template.format(
            summary=summary,
            last_step=last_step.to_str(),
            thought=thought
        )
        
        final_message = [SystemMessage(content=prompt_content)]+scratchpad
        response_model = ActionModel.create(actions)

        structured_llm = self.llm.with_structured_output(response_model)
        llm_out = structured_llm.invoke(final_message)

        return llm_out
