from typing import Dict, Any, Type
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage

from procedures.base_procedure import BaseProcedure


class SummaryModel(BaseModel):
    """
    Structured output model for the SummaryProcedure.
    
    Attributes:
       summary (str): concise summary of the task for agent's reasoning.
       task_reminder (str): key reminder about the current task to guide the agent.
    """
    summary: str = Field(..., title='summary')
    task_reminder: str = Field(..., title='task_reminder')

    class Config:
        @staticmethod
        def json_schema_extra(schema: Dict[str, Any], model: Type['SummaryModel']) -> None:
            """
            Remove unnecessary 'title' fields from the generated JSON schema.
            
            Args:
                schema (Dict[str, Any]): the JSON schema generated by Pydantic
                model (Type['SummaryModel']): the model class.
                """
            for prop in schema.get('properties', {}).values():
                prop.pop('title', None)


class SummaryProcedure(BaseProcedure):
    """A reasoning procedure that invokes the LLM to produce a task-oriented summary of the agent scratchpad.

    This class extends the BaseProcedure to handle reasoning and summary production. 
    It leverages the raw agent scratchpad and the task instructions to produce 
    a task-oriented summary using the LLM.

    Args:
        llm: the LLM responsible for executing tasks based on the prompt.
        prompt_template (str): the prompt template that will be formatted and used as input to the LLM.

    Attributes:
        llm: the LLM responsible for executing tasks based on the prompt.
        prompt_template (str): the prompt template that will be formatted and used as input to the LLM.

    Methods:
        run(context, scratchpad): generates a task-oriented summary based on the given inputs using the LLM.
    """

    def run(self, context: str, scratchpad: list):
        """Execute the summary reasoning procedure based on the current task and
        agent scratchpad

        Args:
            context (str): the description of the current task
            scratchpad (list): the agent scratchpad formatted as messages list

        Returns:
            SummaryModel: the SummaryModel formatted by the LLM
        """
       
        prompt_content = self.prompt_template.format(
            context=context
        )

        final_messages = [SystemMessage(content=prompt_content)] + scratchpad

        structured_llm = self.llm.with_structured_output(SummaryModel)
        
        llm_out = structured_llm.invoke(final_messages)

        return llm_out
