from typing import Dict, Any, Type
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage

from procedures.base_procedure import BaseProcedure
from agents_dir.base_agent import ReActChain

class ThoughtModel(BaseModel):
    """
    Structured output model for the class ThoughtProcedure(BaseProcedure).

    Attributes:
       thought (str): though generated by the agent's reasoning.
    """

    thought: str = Field(..., title='thought')

    class Config:
        @staticmethod
        def json_schema_extra(schema: Dict[str, Any], model: Type['ThoughtModel']) -> None:
            """
            Remove unnecessary 'title' fields from the generated JSON schema.
            
            Args:
                schema (Dict[str, Any]): the JSON schema generated by Pydantic
                model (Type['SummaryModel']): the model class.
            """
            for prop in schema.get('properties', {}).values():
                prop.pop('title', None)


class ThoughtProcedure(BaseProcedure):
    """A reasoning procedure that invokes the LLM to produce a thought on a task.

    This class extends the BaseProcedure to handle reasoning and thought production. 
    It leverages the last agent execution step and the task-oriented summary of 
    the agent scratchpad to produce a thought on the next action using the LLM.

    Args:
        llm: the LLM responsible for executing tasks based on the prompt.
        prompt_template (str): the prompt template that will be formatted and 
            used as input to the LLM.

    Attributes:
        llm: the LLM responsible for executing tasks based on the prompt.
        prompt_template (str): the prompt template that will be formatted and used as input to the LLM.

    Methods:
        run(summary, last_step): generates a thought on the next action based on the given inputs using the LLM.
    """

    def run(self, summary: str, scratchpad: list, last_step: ReActChain):
        """Execute the summary reasoning procedure based on the current task and
        agent scratchpad

        Args:
            summary (str): the produced summary for the current chain.
            last_step (ReActChain): the last step in the reasoning chain, representing the agent's prior thought process.

        Returns:
            ThoughtModel: the ThoughtModel formatted by the LLM
        """
       
        prompt_content = self.prompt_template.format(
            summary=summary,
            last_step=last_step.to_str()
        )


        final_messages = [SystemMessage(content=prompt_content)]+scratchpad

        structured_llm = self.llm.with_structured_output(ThoughtModel)
        llm_out = structured_llm.invoke(final_messages)

        return llm_out
