"""
Module that implements the CreatorAgent, the final stage of the multi-agent pipeline for automated CodeQL query generation.

The CreatorAgent:
    - receives the final report produced by the SuggestorAgent
    - identifies all targeted CWEs that require CodeQL query generation
    - iteratively produces one `.ql` file per CWE using reasoning steps and tool invocations (WriteQuerySubAgent and FinishTool)

Main components:
    - CreatorInput: input model containing the final report of the SuggestorAgent
    - CreatorOutput: final message outputs by the CreatorAgent
    - CreatorAgent: autonomous ReAct agent capable of summarizing context, producing thought, choosing actions and generating 
                    CodeQL queries through available tools.

Workflow:
    1. Summarizing of memory and instructions
    2. Generation of though to decide the next action
    3. Tool-based action execution (WriteQuerySubAgent or FinishTool)
    4. Tracking of processed CWEs until all queries are created.

"""


from pydantic import Field, BaseModel
from typing import Set, Dict
import subprocess
import os

from agents_dir.base_agent import BaseAgent, SharedMemory, BaseTaskInput, ReActChain
from prompts import SUMMARY_TEMPLATE, THOUGHT_TEMPLATE, ACTION_TEMPLATE
from procedures.summ_procedure import SummaryProcedure
from procedures.action_procedure import ActionProcedure
from procedures.tought_procedure import ThoughtProcedure
from config import OUTPUT_QUERIES_PATH

MAX_SEARCHES_PER_CWE = 3

class CreatorInput(BaseTaskInput):
    """
    CreatorAgent input.
    
    Args:
        final_report (str): output report generated by the SuggestorAgent.
    """
    final_report: str = Field(...)

class CreatorOutput(BaseTaskInput):
    """
    CreatorAgent output.
    
    Args:
        final_message (str): final message generated by the CreatorAgent.
    """
    final_message: str = Field(...)


class WriteQueryTool(BaseModel): 
    """"""
    cwe: str = Field(...)
    query_code: str = Field(...)

    def run(self, llm=None) -> str:
        if not self.query_code.strip():
            return "Error: query_cde is empty. Generate the full .ql content before calling WriteQueryTool."
        
        code = self.query_code.strip()
        if code.startswith("```"):
            lines = code.splitlines()
            code = "\n".join(
                line for line in lines
                if not line.strip().startswith("```")
            ).strip()

        os.makedirs(OUTPUT_QUERIES_PATH, exist_ok=True)

        qlpack_path = os.path.join(OUTPUT_QUERIES_PATH, "qlpack.yml")
        if not os.path.exists(qlpack_path):
            with open(qlpack_path, "w") as f:
                f.write("name: custom-python-queries\n")
                f.write("version: 1.0.0\n")
                f.write("dependencies:\n")
                f.write("  codeql/python-all: '*'\n")
        
        safe_filename = self.cwe.replace("-", "_") + ".ql"
        filepath = os.path.join(OUTPUT_QUERIES_PATH, safe_filename)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(code)

        try:
            subprocess.run(
                ["codeql", "pack", "install", OUTPUT_QUERIES_PATH], 
                capture_output=True, text=True, check=True
            )

        except subprocess.CalledProcessError as e:
            return f"Failed to install dependencies."

        result = subprocess.run(
            ["codeql", "query", "compile", "--check-only", filepath],
            capture_output=True, text=True
        )

        if result.returncode == 0:
            return f"SUCCESS: query validated and saved at {filepath}"
        else:
             return (
                f"ERROR compiling {self.cwe}:\n{result.stderr}\n\n"
                f"Analyze the error above. Use WebSearchTool to look up the correct "
                f"CodeQL Python API if a class or predicate is missing, then rewrite "
                f"the query and call WriteQueryTool again."
            )
    
class FinishToolCreator(BaseModel):
    """Tool to signal completion and generate query suite."""
    summary: str = Field(...)



class CreatorAgent(BaseAgent):
    """
    ReAct Agent that has the main role of generating new CodeQL `.ql` files based on the
    report from the SuggestorAgent and the list of targeted CWEs.

    The Agent:
        - reads the last observation and updates the shared memory
        - summarized context and task state usinig SummaryProcedure
        - decides the next step with ThoughtProcedure
        - executes an action with ActionProcedure (WriteQuerySubAgent and FinishTool)
        - executes the tool and converts its output into the next observation
    
    Args: 
        shared_memory (SharedMemory): memory shared among agents
        tools (list): available tools to call when needed
        logpath (str| None=None): file path where logs are saved
        
    Attributes:
        prompt_template (str): a template string for formatting the agent's prompt.
        summ_procedure (SummaryProcedure): summary procedure
        thought_procedure (ThoughtProcedure): reasoning procedure
        action_procedure (ActionProcedure): action procedure
        max_steps (int): maximum number of reasoning steps
        all_cwes (set[str]): full set of CWEs extracted from shared memory
        processed_cwes (set[str]): CWEs for which a CodeQL query was already generated.
    
    Methods:
        reset(task_input): resets the agent state for a new task
        step(observation): execute eache single step of the ReAct cycle
        run(): executed the entire reasoning cycle of the CreatorAgent
    """

    def __init__(self, prompt_template: str, shared_memory: SharedMemory, tools: list, logpath: str | None=None):
        """
        CreatorAgent constructor.
        
        It initializes summary, thought, and action procedures, as well as the CWEs lists.
       
        Args:
            shared_memory (SharedMemory): memory shared among agents
            tools (list): available tools to call when needed
            logpath (str| None=None): file path where logs are saved
        """
        
        super().__init__(prompt_template=prompt_template, shared_memory=shared_memory, tools=tools, logpath=logpath)
        
        self.summ_procedure = SummaryProcedure(self.llm, SUMMARY_TEMPLATE)
        self.thought_procedure = ThoughtProcedure(self.llm, THOUGHT_TEMPLATE)
        self.action_procedure = ActionProcedure(self.llm, ACTION_TEMPLATE)
        self.max_steps = 30
        
        self.all_cwes : Set[str] = set()
        self.processed_cwes : Set[str] = set()
        self.max_trials: dict = {}
        self.current_cwe = ""



    def reset(self, task_input: BaseTaskInput) -> None:
        """
        Resets the agent state for a new task.

        This methods:
            - stores the final suggestor report 
            - loads the list of the targets CWEs from shared memory
            - resets "processed_cwes"
            - create a clerare final observation with more precise instructions-

        Args:
            task_input (CreatorInput): task input.
        """

        super().reset(task_input)
        if not isinstance(task_input, CreatorInput):
            return
        
        self.report = task_input.final_report.replace('"', "'")
        self.all_cwes = set(self.shared_memory.get_data("suggestor_processed_cwes") or [])
        self.processed_cwes.clear()
        self.max_trials.clear()
        self.existing_queries = self.shared_memory.get_data("existing_queries", {})


        pending = self.all_cwes - self.processed_cwes
        self.current_cwe = sorted(pending)[0] if pending else ""
        self.last_step.observation = (
            f"SuggestorAgent report loaded. CWEs to process: {sorted(self.all_cwes)}.\n"
            f"For each CWE, write the complete .ql query content and call WriteQueryTool.\n"
            f"When using WebSearchTool, pass cwe='CWE-XX' to bind results to the right CWE.\n"
            f"Start with: {sorted(pending)[0] if pending else 'none'}."
        )
            
    def summarize(self, query: str, text: str) -> str:
        if len(text)< 1000:
            return text

        summary_prompt = f"""
        Analyze the following web search result for the query: "{query}".
        Extract only the relevanti informations like:
        - the CodeQL classes, predicates or library names mentioned.
        - specific AST elements (Sources, Sinks).
        - code snippets or logic patterns for TainTracking.
        Discard all navigation menus, ads and irrelevant prose.
        Result to summarize: {text[:8000]}
        """

        response = self.llm.invoke(summary_prompt)
        return f"Compressed web search result: {response.content}"
    
    def step(self, observation: str) -> ReActChain:
        """
        Executes a single reasoning-action step using the ReAct pattern.
        
        The cycle includes:
        1. memory update
        2. summary generation
        3. reasoning (thought)
        4. selection/creation next action

        Args: 
            observation (str): new observation to process
        
        Returns:
            ReActChain: updated chain containing summary, thought and action.
        """

        self.update_memory(observation)
        scratchpad = self.shared_memory.to_messages()[-10:]
        pending = self.all_cwes - self.processed_cwes
        eq_text = ""
        for cwe in sorted(pending):
            q = self.existing_queries.get(cwe, "")
            if q:
                eq_text += f"\n=== EXISTING QUERY FOR {cwe} ===\n{q[:4000]}\n"
            

        instructions = self.prompt_template.format(
            all_cwes       = ", ".join(sorted(self.all_cwes)),
            report         = self.report,
            processed_cwes = ", ".join(sorted(self.processed_cwes)),
            pending_cwes   = ", ".join(sorted(pending)),
            existing_queries = eq_text
        )

        summary_out = self.summ_procedure.run(instructions, scratchpad)
        summary = summary_out.summary

        thought_out =self.thought_procedure.run(summary, scratchpad, self.last_step)
        thought = thought_out.thought

        action_out = self.action_procedure.run(summary, scratchpad, self.last_step, thought, self.tools)
        action = action_out.action
    
        self.last_step = ReActChain.format(summary=summary, thought=thought, action=action)
        return self.last_step
    

    def run(self) -> CreatorOutput:
        """
        Executes the full CodeQL query creation loop.
        
        Workflow:
            - iteratively run reasoning steps up to max_steps.
            - on each step, detect which tool was selected (WriteQuerySubAgent or FinishTool).
            - handles erorrs such as duplicate CWE attempts.
        
        Returns:
            CreatorOutput: contains final message generated by the CreatorAgent

        Raises:
            TimeoutError: if the agent exceed max_steps.
        """

        pending = self.all_cwes - self.processed_cwes
        search_count: Dict[str, int] = {}
        last_observation = (
            f"Report loaded. Generate .ql queries for: {sorted(self.all_cwes)}. "
            f"Write the full query code in your reasoning, then call WriteQueryTool."
        )        

        for step in range(self.max_steps):

            current_reasoning = self.step(last_observation)
            current_action = current_reasoning.action

            if not current_action:
                pending = self.all_cwes - self.processed_cwes
                last_observation = (
                    f"ERROR: no action chosen. "
                    f"Pending CWEs: {sorted(pending)}. "
                    f"Use WebSearchTool(query=..., cwe='CWE-XX') if needed, then call "
                    f"WriteQueryTool(cwe=..., query_code=...)."
                )
                self.update_memory(last_observation)
                continue

            action_name = current_action.__class__.__name__
            pending = self.all_cwes - self.processed_cwes
            if pending and self.current_cwe not in pending:
                self.current_cwe = sorted(pending)[0]
            

            print(f"\n[{step}] {action_name} | Pending: {pending}")
            print(f"    Thought: {current_reasoning.thought[:120]}...")

            if action_name == "FinishToolCreator":
                if pending:
                    last_observation = (f"BLOCKED: cannot finish. Pending CWEs: {sorted(pending)}. "
                        f"Call WriteQueryTool for each remaining CWE first."
                    )
                    self.update_memory(last_observation)
                    continue

                summary = getattr(current_action, "summary", "")
                created = sorted(self.processed_cwes)
                print(f"[Creator] Done. Created queries for: {created}")
                
                return CreatorOutput(
                    final_message=f"Queries created for: {created}. {summary}"
                )
            
            if action_name == "WebSearchTool":
                try:
                    result = current_action.run()
                    query = getattr(current_action, "query", "")
                    compressed = self.summarize(query, str(result))
                    explicit_cwe = getattr(current_action, "cwe", "").strip()
                    if explicit_cwe in self.all_cwes:
                        target_cwe = explicit_cwe
                    else:
                        target_cwe = self.current_cwe

                    if target_cwe:
                        search_count[target_cwe] = search_count.get(target_cwe, 0)+1
                    
                    cwe_searches = search_count.get(target_cwe, 0) if target_cwe else sum(search_count.values())

                    if target_cwe and cwe_searches >= MAX_SEARCHES_PER_CWE:
                        last_observation = (
                            f"WebSearchTool result for '{target_cwe}':\n{compressed[:800]}\n\n"
                            f"Search limit reached for {target_cwe}. "
                            f"Call WriteQueryTool(cwe={target_cwe}, query_code=...) now."
                        )
               
                    else:
                        last_observation = (
                            f"WebSearch result:\n{str(result)[:1500]}\n\n"
                            f"Use this information to write or fix the .ql query, "
                            f"then call WriteQueryTool."
                        )
                except Exception as e:
                    last_observation = f"WebSearch error: {e}. Try a different query or proceed."


            elif action_name == "WriteQueryTool":
                cwe = getattr(current_action, "cwe", "").strip()
                if not cwe or cwe not in self.all_cwes:
                    last_observation = (
                         f"Invalid CWE '{cwe}'. Valid CWEs: {sorted(self.all_cwes)}."
                    )
                    self.update_memory(last_observation)
                    continue
                if cwe in self.processed_cwes:
                    remaining = self.all_cwes - self.processed_cwes
                    next_cwe = sorted(remaining)[0] if remaining else None
                    self.current_cwe = next_cwe or ""
                    last_observation = (
                        f"BLOCKED: {cwe} already processed/skipped. Do NOT retry it.\n"
                        f"{'Remaining: ' + str(sorted(remaining)) + '. Write query for ' + next_cwe + ' now.' if next_cwe else 'All done. Call FinishToolCreator.'}"
                    )
                    self.update_memory(last_observation)
                    continue
            
                try:
                    self.current_cwe = cwe 
                    result = current_action.run()
                except Exception as e:
                    result = f"ERROR: {e}"

                if result.startswith("SUCCESS"):
                    self.processed_cwes.add(cwe)
                    self.max_trials.pop(cwe, None)
                    remaining = self.all_cwes - self.processed_cwes
                    next_cwe = sorted(remaining)[0] if remaining else None
                    self.current_cwe = next_cwe or ""
                    print(f"{cwe} done | Remaining: {remaining}")

                    if remaining:
                        last_observation = (
                            f"SUCCESS: {cwe} query saved.\n"
                            f"Remaining CWEs: {sorted(remaining)}.\n"
                            f"Write the next query and call WriteQueryTool."             
                        )
                    else:
                        last_observation = (
                            f"SUCCESS: {cwe} query saved.\n"
                            f"All CWEs processed. Call FinishToolCreator."
                        )
                
                else:
                    self.max_trials[cwe] = self.max_trials.get(cwe, 0)+1
                    attempt = self.max_trials[cwe]
                    print(f"{cwe} attempt {attempt}/3")

                    if attempt >= 3:
                        self.processed_cwes.add(cwe)
                        remaining = self.all_cwes - self.processed_cwes
                        next_cwe = sorted(remaining)[0] if remaining else None
                        self.current_cwe = next_cwe or ""

                        # Il file è già su disco scritto da WriteQueryTool
                        # lo rinominiamo con suffisso _failed per distinguerlo
                        safe_filename = cwe.replace("-", "_") + ".ql"
                        filepath = os.path.join(OUTPUT_QUERIES_PATH, safe_filename)
                        failed_path = filepath.replace(".ql", "_failed.ql")

                        if os.path.exists(filepath):
                            os.rename(filepath, failed_path)
                            print(f"{cwe} skipped — query non compilabile dopo 3 tentativi")
                            print(f"   File salvato per ispezione: {failed_path}")
                        else:
                            print(f"{cwe} skipped — file non trovato su disco")

                        last_observation = (
                            f"{cwe} failed 3 times - skipped.\n"
                            f"{'Next CWE: ' + next_cwe + '. Write query for ' + next_cwe + ' now.' if next_cwe else 'All done. Call FinishToolCreator.'}"
                        )
                        print(f"{cwe} skipped after 3 failures")

            else:
                last_observation = (
                    f"Unknown tool: {action_name}. "
                    f"Available: WebSearchTool, WriteQueryTool, FinishToolCreator."
                )

            self.update_memory(last_observation)

        raise TimeoutError(
            f"Creator exceeded max_steps={self.max_steps}. "
            f"Processed: {self.processed_cwes} | Pending: {self.all_cwes - self.processed_cwes}"
        )        
